services:
  ipc-api:
    build: .
    container_name: alquiler-IPC

    env_file: .env
    expose:
      - "8000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
