services:
  ipc-api:
    build: .
    container_name: alquiler-IPC

    env_file: .env
    expose:
      - "8000"
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      Alquiler_tunn_net:
        aliases: [alquiler-IPC]

networks:
  Alquiler_tunn_net:
    name: Alquiler_tunn_net
    external: true
